### PR TITLE
Adding faq

### PR DESCRIPTION
**Pull request by fer-rum**
I created a draft FAQ page, reachable from the index page.
It would be cool, if someone could add a message box there, instead of just having a hard coded link.
Also, the recipient should be automatically inserted and not hard coded.

Make these changes before pulling!

### CODE REVIEW

**Comment by fer-rum** [comment]
Also, this will probably need to be included properly into the url configuration, which I obviously was unable to do.

**Comment by JustusAdam** [comment]
Is there not a view missing that actually serves the faq page?

**Comment by JustusAdam** [comment]
If the actual view/url config is missing, shouldn't we wait to merge it?

**Comment by fer-rum** [comment]
See my second comment. If I were able to do it properly, I would.

**Comment by ManuelvOK** [comment]
Added the routing

**Pull request merged**
